version: 2

workflows:
  experiment-workflow:
    steps:
      -
        name: "training"
        command: experiment.run_single_node
        params:
          command: pip install -r requirements.txt && python train.py
          container: tensorflow/tensorflow:2.4.1-gpu
          machineType: P4000
          modelPath: /artifacts
          modelType: Tensorflow
          name: deep-taste-cli-config-yaml